const INVENTORY_MOVEMENTS = Object.freeze({
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  RETURN_CUSTOMER: "RETURN_CUSTOMER",
  RETURN_SUPPLIER: "RETURN_SUPPLIER",
  SELF_CONSUMPTION: "SELF_CONSUMPTION",
  DAMAGE: "DAMAGE",
  ADJUSTMENT: "ADJUSTMENT",
});

module.exports = INVENTORY_MOVEMENTS;