module.exports = {
  PURCHASE: "PURCHASE",
  SALE: "SALE",

  CUSTOMER_RETURN: "CUSTOMER_RETURN",
  SUPPLIER_RETURN: "SUPPLIER_RETURN",

  SELF_CONSUMPTION: "SELF_CONSUMPTION",

  DAMAGE: "DAMAGE",

  FOUND: "FOUND",

  MANUAL_IN: "MANUAL_IN",
  MANUAL_OUT: "MANUAL_OUT"
};